/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { NMKRClient } from './NMKRClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AdditionalPayoutWalletsClass } from './models/AdditionalPayoutWalletsClass';
export type { AddressType } from './models/AddressType';
export type { ApiErrorResultClass } from './models/ApiErrorResultClass';
export type { AssetsAssociatedWithAccount } from './models/AssetsAssociatedWithAccount';
export type { AuctionsHistory } from './models/AuctionsHistory';
export type { AuctionsNft } from './models/AuctionsNft';
export type { BackgroundTaskEnums } from './models/BackgroundTaskEnums';
export type { Blockchain } from './models/Blockchain';
export type { CheckAddressResultClass } from './models/CheckAddressResultClass';
export type { CheckConditionsResultClass } from './models/CheckConditionsResultClass';
export type { CheckDiscountsResultClass } from './models/CheckDiscountsResultClass';
export type { CheckWalletValidationResultClass } from './models/CheckWalletValidationResultClass';
export type { Coin } from './models/Coin';
export type { CountedWhitelistAddressesClass } from './models/CountedWhitelistAddressesClass';
export type { CreateAuctionClass } from './models/CreateAuctionClass';
export type { CreateBurningEndpointClass } from './models/CreateBurningEndpointClass';
export type { CreateManagedWalletClass } from './models/CreateManagedWalletClass';
export type { CreateManagedWalletTransactionClass } from './models/CreateManagedWalletTransactionClass';
export type { CreateNewProjectResultClass } from './models/CreateNewProjectResultClass';
export type { CreateProjectClassV2 } from './models/CreateProjectClassV2';
export type { CreateSplitAddressClass } from './models/CreateSplitAddressClass';
export type { CreateSplits } from './models/CreateSplits';
export type { CreateSubcustomerApikeyClass } from './models/CreateSubcustomerApikeyClass';
export type { CreateSubcustomerClass } from './models/CreateSubcustomerClass';
export type { CreateSubcustomerResultClass } from './models/CreateSubcustomerResultClass';
export type { CreateVestingAddressClass } from './models/CreateVestingAddressClass';
export type { CreateVestingAddressResultClass } from './models/CreateVestingAddressResultClass';
export type { CreateWalletResultClass } from './models/CreateWalletResultClass';
export type { CryptoCoin } from './models/CryptoCoin';
export type { CurrencyTypes } from './models/CurrencyTypes';
export type { Dataproviders } from './models/Dataproviders';
export type { DecentralParametersResultClass } from './models/DecentralParametersResultClass';
export type { DeleteAllNftsDetail } from './models/DeleteAllNftsDetail';
export type { DeleteAllNftsResultClass } from './models/DeleteAllNftsResultClass';
export type { DuplicateNftClass } from './models/DuplicateNftClass';
export type { FrankenAddressProtectionClass } from './models/FrankenAddressProtectionClass';
export type { GetAllUploadedFilesResultClass } from './models/GetAllUploadedFilesResultClass';
export type { GetAuctionsClass } from './models/GetAuctionsClass';
export type { GetAuctionStateResultClass } from './models/GetAuctionStateResultClass';
export type { GetDiscountsClass } from './models/GetDiscountsClass';
export type { GetKeyHashClass } from './models/GetKeyHashClass';
export type { GetMintCouponBalanceResultClass } from './models/GetMintCouponBalanceResultClass';
export type { GetNmkrPayLinkClass } from './models/GetNmkrPayLinkClass';
export type { GetNmkrPayLinkResultClass } from './models/GetNmkrPayLinkResultClass';
export type { GetNotificationsClass } from './models/GetNotificationsClass';
export type { GetPaymentAddressResultClass } from './models/GetPaymentAddressResultClass';
export type { GetPayoutWalletsResultClass } from './models/GetPayoutWalletsResultClass';
export type { GetRefundsClass } from './models/GetRefundsClass';
export type { GetSaleconditionsClass } from './models/GetSaleconditionsClass';
export type { GetSplitAddressClass } from './models/GetSplitAddressClass';
export type { GetSplits } from './models/GetSplits';
export type { GetTransactionNftsClass } from './models/GetTransactionNftsClass';
export type { GetTransactionsClass } from './models/GetTransactionsClass';
export type { GetVestingAddressClass } from './models/GetVestingAddressClass';
export type { GetWalletValidationAddressResultClass } from './models/GetWalletValidationAddressResultClass';
export type { GetWhitelistEntriesClass } from './models/GetWhitelistEntriesClass';
export type { IdentityInformationClass } from './models/IdentityInformationClass';
export type { ImportManagedWalletClass } from './models/ImportManagedWalletClass';
export type { ImportWalletResultClass } from './models/ImportWalletResultClass';
export type { MakeTransactionResultClass } from './models/MakeTransactionResultClass';
export type { MakeTransactionResults } from './models/MakeTransactionResults';
export type { MetadataPlaceholderClass } from './models/MetadataPlaceholderClass';
export type { MintAndSendResultClass } from './models/MintAndSendResultClass';
export type { MintingTransactionInformation } from './models/MintingTransactionInformation';
export type { MintNftsClass } from './models/MintNftsClass';
export type { MintNftsResultClass } from './models/MintNftsResultClass';
export type { NFT } from './models/NFT';
export type { NftCountsClass } from './models/NftCountsClass';
export type { NftDetailsClass } from './models/NftDetailsClass';
export type { NftFileV2 } from './models/NftFileV2';
export type { NftProjectsDetails } from './models/NftProjectsDetails';
export type { NftSubfileFileV2 } from './models/NftSubfileFileV2';
export type { NmkrAccountOptionsTypes } from './models/NmkrAccountOptionsTypes';
export type { NmkrAssetAddress } from './models/NmkrAssetAddress';
export type { NmkrPayPaymentgatewayParamatersClass } from './models/NmkrPayPaymentgatewayParamatersClass';
export type { NmkrPayTransactionTypes } from './models/NmkrPayTransactionTypes';
export type { NotificationsClassV2 } from './models/NotificationsClassV2';
export type { PaymentgatewayParametersClass } from './models/PaymentgatewayParametersClass';
export type { PaymentTransactionNotificationsClass } from './models/PaymentTransactionNotificationsClass';
export type { PaymentTransactionNotificationTypes } from './models/PaymentTransactionNotificationTypes';
export type { PaymentTransactionsStates } from './models/PaymentTransactionsStates';
export type { PaymentTransactionSubstates } from './models/PaymentTransactionSubstates';
export type { PaymentTransactionTypes } from './models/PaymentTransactionTypes';
export type { PayoutWalletsClassV2 } from './models/PayoutWalletsClassV2';
export type { PayoutWalletState } from './models/PayoutWalletState';
export type { PolicyClass } from './models/PolicyClass';
export type { PriceDiscountClassV2 } from './models/PriceDiscountClassV2';
export type { PricelistClass } from './models/PricelistClass';
export type { PricelistClassV2 } from './models/PricelistClassV2';
export type { PricelistDiscountTypes } from './models/PricelistDiscountTypes';
export type { ProblemDetails } from './models/ProblemDetails';
export type { ProjectSortOptions } from './models/ProjectSortOptions';
export type { PublicMintsClass } from './models/PublicMintsClass';
export type { PublicMintState } from './models/PublicMintState';
export type { RatesClass } from './models/RatesClass';
export type { ReservedNftsClassV2 } from './models/ReservedNftsClassV2';
export type { ReserveMultipleNftsClassV2 } from './models/ReserveMultipleNftsClassV2';
export type { ReserveNftsClassV2 } from './models/ReserveNftsClassV2';
export type { ResultStates } from './models/ResultStates';
export type { RoyaltyClass } from './models/RoyaltyClass';
export type { SaleconditionsClassV2 } from './models/SaleconditionsClassV2';
export type { SaleConditionsTypes } from './models/SaleConditionsTypes';
export type { SendAllAssetsTransactionClass } from './models/SendAllAssetsTransactionClass';
export type { ServerStateClass } from './models/ServerStateClass';
export type { SolanaProjectDetails } from './models/SolanaProjectDetails';
export type { SoldNftsOrTokensFromWhitelist } from './models/SoldNftsOrTokensFromWhitelist';
export type { SubcustomerClass } from './models/SubcustomerClass';
export type { SubcustomerMintcouponPayinAddresses } from './models/SubcustomerMintcouponPayinAddresses';
export type { TokenRegistryMetadata } from './models/TokenRegistryMetadata';
export type { Tokens } from './models/Tokens';
export type { TransactionReceiversClass } from './models/TransactionReceiversClass';
export type { TransactionsExportOptions } from './models/TransactionsExportOptions';
export type { TransactionTokensClass } from './models/TransactionTokensClass';
export type { TxInAddressesClass } from './models/TxInAddressesClass';
export type { TxInClass } from './models/TxInClass';
export type { TxInTokensClass } from './models/TxInTokensClass';
export type { UploadMetadataClass } from './models/UploadMetadataClass';
export type { UploadNftClassV2 } from './models/UploadNftClassV2';
export type { UploadNftResultClass } from './models/UploadNftResultClass';
export type { UploadToIpfsClass } from './models/UploadToIpfsClass';
export type { Wallets } from './models/Wallets';
export type { WhitelistetedCountClass } from './models/WhitelistetedCountClass';

export { AddressReservationSaleService } from './services/AddressReservationSaleService';
export { AuctionsService } from './services/AuctionsService';
export { CustomerService } from './services/CustomerService';
export { IpfsService } from './services/IpfsService';
export { ManagedWalletsService } from './services/ManagedWalletsService';
export { MintService } from './services/MintService';
export { MiscService } from './services/MiscService';
export { NftService } from './services/NftService';
export { NmkrPayService } from './services/NmkrPayService';
export { ProjectsService } from './services/ProjectsService';
export { SplitAddressesService } from './services/SplitAddressesService';
export { ToolsService } from './services/ToolsService';
export { VestingAddressesService } from './services/VestingAddressesService';
export { WalletValidationService } from './services/WalletValidationService';
export { WhitelistsService } from './services/WhitelistsService';
