/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type BackgroundTaskEnums =
  | 'executedatabasecommands'
  | 'checkfreepaymentaddresses'
  | 'checkcustomeraddresses'
  | 'checkadminmintingaddresses'
  | 'checkpaymentaddresses'
  | 'checkpremintedaddresses'
  | 'checkburningaddresses'
  | 'checkexpiredpaymentaddresses'
  | 'checkexpiredpremintedaddresses'
  | 'checkexpiredreservations'
  | 'executepayouts'
  | 'checkpolicies'
  | 'checkdoublepayments'
  | 'checkpayinaddresses'
  | 'mintandsend'
  | 'checkvalidationaddresses'
  | 'checklegacyauctions'
  | 'checklegacydirectsales'
  | 'checknotificationqueue'
  | 'executesubmissions'
  | 'checkdecentralsubmits'
  | 'checkroyaltysplitaddresses'
  | 'none'
  | 'checktransactionconfirmations'
  | 'checkbuyinsmartcontractaddresses'
  | 'checkcustomerchargeaddresses'
  | 'checkpaymentaddressessolana'
  | 'mintandsendsolana'
  | 'checkpoliciessolana'
  | 'checkcustomeraddressessolana'
  | 'checkrates';
